config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/apis', to: 'apis#index'
  root to: 'home#index'
  resources :periodicities, only: %i[index create update edit destroy]
  resources :product_types, only: %i[index create update edit destroy]
  resources :plans, only: %i[index create update edit destroy] do
    post 'deactivate', 'activate', on: :member
  end
  resources :prices, only: %i[index create update edit destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :periodicities, only: :index
      resources :product_types, only: %i[index show] do
        resources :plans, only: :index, action: :product_type
      end
      resources :plans, only: %i[index show] do
        resources :prices, only: :index
      end
    end
  end
end

app/controllers/api/v1/product_types_controller.rb
class Api::V1::ProductTypesController < Api::V1::ApiController
  # Rota para todas os produtos
  #
  # = Exemplo de Request
  #   GET /api/v1/product_types
  #
  # = Exemplo de Response
  #   => Status Code: 200 OK
  # [
  #   {
  #   "id": 1,
  #   "name": "Hospedagem de sites",
  #   "description": "É um espaço em servidor para que você possa armazenar o seu site.",
  #   "product_key": "HEMS8019",
  #   "created_at": "2021-03-13T20:18:19.470Z",
  #   "updated_at": "2021-03-13T20:18:19.470Z"
  #   },
  #   {
  #   "id": 2,
  #   "name": "Email",
  #   "description": "É um serviço de correio eletrônico para envios e recebimentos de mensagens.",
  #   "product_key": "EAIL6486",
  #   "created_at": "2021-03-13T20:18:19.482Z",
  #   "updated_at": "2021-03-13T20:18:19.482Z"
  #   }
  # ]
  def index
    render json: ProductType.all, status: :ok
  end

  # Rota para um produto
  #
  # = Exemplo de Request
  #   GET /api/v1/product_types/:id
  #
  # = Exemplo de Response
  #   => Status Code: 200 OK
  # {
  #   "id": 1,
  #   "name": "Hospedagem de sites",
  #   "description": "É um espaço em servidor para que você possa armazenar o seu site.",
  #   "product_key": "HEMS8019",
  #   "created_at": "2021-03-13T20:18:19.470Z",
  #   "updated_at": "2021-03-13T20:18:19.470Z"
  # }
  def show
    product = ProductType.find_by(id: find_product.fetch(:id))
    if product.present?
      render json: product, status: :ok
    else
      render body: nil, status: :not_found
    end
  end


  private

  def find_product
    params.permit(:id)
  end
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :product_types_all, only: %i[index create]

  def index
    @product_type = ProductType.new
  end

  def create
    @product_type = ProductType.new(product_type_params)
    return redirect_back fallback_location: product_types_path,
                         notice: t('.success') if @product_type.save

    flash.now[:alert] = t('.error')
    render :index
  end

  def edit
    @product_type = ProductType.find(params[:id])
  end

  def update
    @product_type = ProductType.find(params[:id])
    return redirect_to product_types_path, notice: t('.success') \
           if @product_type.update(product_type_params)

    flash.now[:alert] = t('.error')
    render :edit
  end

  def destroy
    ProductType.destroy(params[:id])
    redirect_back fallback_location: product_types_path,
                  notice: t('.success')
  end

  private

  def product_types_all
    @product_types = ProductType.all
  end

  def product_type_params
    params.require(:product_type).permit(:name, :description, :product_key)
  end
end

app/views/product_types/_form.html.erb
<%= form_with model: @product_type, local: true, 
              class: 'ls-form ls-form-horizontal' do | form |%>
  <div class="ls-modal-body" id="myModalBody">
    <fieldset>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :description %>
        <%= form.text_field :description %>
      </label>
    </fieldset>
  </div>
  <div class="ls-modal-footer">
    <%= form.submit class: 'ls-btn-primary' %>
  </div>
<% end %>

app/views/product_types/_modal.html.erb
<div class="ls-modal" id="addProductType">
  <div class="ls-modal-box">
    <div class="ls-modal-header">
      <button data-dismiss="modal">&times;</button>
      <h4 class="ls-modal-title"><%= t('.title') %></h4>
    </div>
    <%= render 'form' %>
  </div>
    </div>

app/views/product_types/edit.html.erb
 <h1 class="ls-title-intro ls-ico-calendar"><%= t('.title') %></h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @product_type.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @product_type.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<%= render 'form' %>

app/views/product_types/index.html.erb
 <h1 class="ls-title-intro ls-ico-origins">
  <%= ProductType.model_name.human(count: 2) %>
</h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @product_type.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @product_type.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<button data-ls-module="modal" data-target="#addProductType" 
        class="ls-btn-primary ls-ico-origins"> <%= t('.add_button') %>
</button>

 <table class="ls-table ls-table-striped">
  <thead>
    <tr>
      <th class="hidden-xs"><%= ProductType.human_attribute_name('id') %></th>
      <th><%= ProductType.human_attribute_name('name') %></th>
      <th class="hidden-xs"><%= ProductType.human_attribute_name('description') %></th>
      <th><%= ProductType.human_attribute_name('product_key') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @product_types.each do | product | %>
    <tr id=<%= "product-#{product.id}" %>>
      <td class="hidden-xs"><%= product.id %></td>
      <td><%= product.name %></td>
      <td class="hidden-xs"><%= product.description %></td>
      <td><%= product.product_key %></td>
      <td class="hidden-xs">
        <%= link_to t('.edit_button'), edit_product_type_path(product), class: 'ls-btn' %> 
        <%= link_to '', product, method: :delete, class: 'ls-btn-primary-danger ls-ico-remove',
                                     data: { confirm: t('.confirmation_deletion') }, 
                                     id: 'deletar_button' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'modal' %>

<br><br>