config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/apis', to: 'apis#index'
  root to: 'home#index'
  resources :periodicities, only: %i[index create update edit destroy]
  resources :product_types, only: %i[index create update edit destroy]
  resources :plans, only: %i[index create update edit destroy] do
    post 'deactivate', 'activate', on: :member
  end
  resources :prices, only: %i[index create update edit destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :periodicities, only: :index
      resources :product_types, only: %i[index show] do
        resources :plans, only: :index, action: :product_type
      end
      resources :plans, only: %i[index show] do
        resources :prices, only: :index
      end
    end
  end
end

app/models/periodicity.rb
class Periodicity < ApplicationRecord
  validates :name, :period, presence: true
  validates :name, inclusion: { in: %w[Mensal Trimestral Semestral
                                       Anual Trienal] }
  validates :period, inclusion: { in: [1, 3, 6, 12, 36] }
  validates :period, numericality: { only_integer: true }
  validates :name, :period, uniqueness: true

  before_validation :normalize_name, on: %i[create update]
  before_validation :set_period, on: %i[create update]

  private

  def normalize_name
    return unless name

    self.name = name.downcase.capitalize
  end

  def set_period
    case name
    when 'Mensal' then self.period = 1
    when 'Trimestral' then self.period = 3
    when 'Semestral' then self.period = 6
    when 'Anual' then self.period = 12
    when 'Trienal' then self.period = 36
    end
  end
end

app/controllers/api/v1/periodicities_controller.rb
class Api::V1::PeriodicitiesController < Api::V1::ApiController
  # Rota para todas as periodicidades
  #
  # = Exemplo de Request
  #   GET /api/v1/periodicities
  #
  # = Exemplo de Response
  #   => Status Code: 200 OK
  # [
  #   {
  #   "id": 1,
  #   "name": "Mensal",
  #   "period": 1,
  #   "created_at": "2021-03-13T20:18:19.259Z",
  #   "updated_at": "2021-03-13T20:18:19.259Z"
  #   },
  #   {
  #   "id": 2,
  #   "name": "Trimestral",
  #   "period": 3,
  #   "created_at": "2021-03-13T20:18:19.300Z",
  #   "updated_at": "2021-03-13T20:18:19.300Z"
  #   }
  # ]
  def index
    render json: Periodicity.all, status: :ok
  end
end

app/controllers/periodicities_controller.rb
class PeriodicitiesController < ApplicationController
  before_action :periodicities_all, only: %i[index create]

  def index
    @periodicity = Periodicity.new
  end

  def create
    @periodicity = Periodicity.new(periodicity_params)
    return redirect_to periodicities_path, notice: t('.success') \
           if @periodicity.save

    flash.now[:alert] = t('.error')
    render :index
  end

  def edit
    @periodicity = Periodicity.find(params[:id])
  end

  def update
    @periodicity = Periodicity.find(params[:id])
    return redirect_to periodicities_path, notice: t('.success') \
           if @periodicity.update(periodicity_params)

    flash.now[:alert] = t('.error')
    render :edit
  end

  def destroy
    Periodicity.destroy(params[:id])
    redirect_back fallback_location: periodicities_path,
                  notice: t('.success')
  end

  private

  def periodicities_all
    @periodicities = Periodicity.all
  end

  def periodicity_params
    params.require(:periodicity).permit(:name, :period)
  end
end

app/views/periodicities/_form.html.erb
<%= form_with model: @periodicity, local: true, 
              class: 'ls-form ls-form-horizontal' do | form |%>
  <div class="ls-modal-body" id="myModalBody">
    <fieldset>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </label>
    </fieldset> 
  </div>
  <div class="ls-modal-footer">
    <%= form.submit class: 'ls-btn-primary' %>
  </div>
<% end %>

app/views/periodicities/_modal.html.erb
<div class="ls-modal" id="addPeriodicity">
  <div class="ls-modal-box">
    <div class="ls-modal-header">
      <button data-dismiss="modal">&times;</button>
      <h4 class="ls-modal-title"><%= t('.title') %></h4>
    </div>
    <%= render 'form' %>
  </div>
</div>

app/views/periodicities/edit.html.erb
 <h1 class="ls-title-intro ls-ico-calendar"><%= t('.title') %></h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @periodicity.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @periodicity.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<%= render 'form' %>

app/views/periodicities/index.html.erb
 <h1 class="ls-title-intro ls-ico-calendar">
  <%= Periodicity.model_name.human(count: 2) %>
</h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @periodicity.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @periodicity.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<button data-ls-module="modal" data-target="#addPeriodicity" 
        class="ls-btn-primary ls-ico-calendar"> <%= t('.add_button') %>
</button>

 <table class="ls-table ls-table-striped">
  <thead>
    <tr>
      <th class="hidden-xs">
        <%= Periodicity.human_attribute_name('id') %>
      </th>
      <th>
        <%= Periodicity.human_attribute_name('name') %>
      </th>
      <th class="hidden-xs">
        <%= Periodicity.human_attribute_name('period') %>
        (<%= t('.sub_text_column_period') %>)
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @periodicities.each do | periodicity | %>
    <tr id=<%= "periodicity-#{periodicity.id}" %>>
      <td class="hidden-xs"><%= periodicity.id %></td>
      <td><%= periodicity.name %></td>
      <td class="hidden-xs"><%= periodicity.period %></td>
      <td>
        <%= link_to t('.edit_button'), edit_periodicity_path(periodicity), class: 'ls-btn' %> 
        <%= link_to '', periodicity, method: :delete, class: 'ls-btn-primary-danger ls-ico-remove',
                                     data: { confirm: t('.confirmation_deletion') }, 
                                     id: 'deletar_button' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'modal' %>

<br><br>