config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/apis', to: 'apis#index'
  root to: 'home#index'
  resources :periodicities, only: %i[index create update edit destroy]
  resources :product_types, only: %i[index create update edit destroy]
  resources :plans, only: %i[index create update edit destroy] do
    post 'deactivate', 'activate', on: :member
  end
  resources :prices, only: %i[index create update edit destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :periodicities, only: :index
      resources :product_types, only: %i[index show] do
        resources :plans, only: :index, action: :product_type
      end
      resources :plans, only: %i[index show] do
        resources :prices, only: :index
      end
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :product_type
  has_many :prices, dependent: :destroy

  enum status: { activated: 0, disabled: 5 }
  validates :name, :description, :details, :status, presence: true
  validates :name, uniqueness: true
end

app/controllers/api/v1/plans_controller.rb
class Api::V1::PlansController < Api::V1::ApiController
  # Rota para todas os planos
  #
  # = Exemplo de Request
  #   GET /api/v1/plans
  #
  # = Exemplo de Response
  #   => Status Code: 200 OK
  # [
  #   {
  #   "id": 2,
  #   "name": "Initial",
  #   "description": "25 caixas postais, 15 GB por caixa A partir de R$ 1,05 por caixa.",
  #   "product_type_id": 2,
  #   "details": "Antispam e antivírus, Aplicativo Type App, Painel de controle, Versão mobile.",
  #   "created_at": "2021-03-13T20:18:19.624Z",
  #   "updated_at": "2021-03-13T20:18:19.624Z",
  #   "status": "activated"
  #   },
  #   {
  #   "id": 3,
  #   "name": "Cloud pro 1 gb",
  #   "description": "1 GB de memória, 2 vCPUs, 20 GB de disco SSD 1 TB de transferência.",
  #   "product_type_id": 3,
  #   "details": "Disco SSD, Escalabilidade vertical Acesso Root/Admin, Serviços adicionais.",
  #   "created_at": "2021-03-13T20:18:19.707Z",
  #   "updated_at": "2021-03-13T20:18:19.707Z",
  #   "status": "disabled"
  #   }
  # ]
  def index
    render json: Plan.all, status: :ok
  end

  # Rota para um plano
  #
  # = Exemplo de Request
  #   GET /api/v1/plans/:id
  #
  # = Exemplo de Response
  #   => Status Code: 200 OK
  # {
  #   "id": 2,
  #   "name": "Initial",
  #   "description": "25 caixas postais, 15 GB por caixa A partir de R$ 1,05 por caixa.",
  #   "product_type_id": 2,
  #   "details": "Antispam e antivírus, Aplicativo Type App, Painel de controle, Versão mobile.",
  #   "created_at": "2021-03-13T20:18:19.624Z",
  #   "updated_at": "2021-03-13T20:18:19.624Z",
  #   "status": "activated"
  # }
  def show
    plan = Plan.find_by(id: find_plan.fetch(:id))
    if plan.present?
      render json: plan, status: :ok
    else
      render body: nil, status: :not_found
    end
  end

  # Rota para planos de um produto específico
  #
  # = Exemplo de Request
  #   GET /api/v1/product_types/:product_type_id/plans
  #
  # = Exemplo de Response
  #   => Status Code: 200 OK
  # [
  #   {
  #   "id": 2,
  #   "name": "Initial",
  #   "description": "25 caixas postais, 15 GB por caixa A partir de R$ 1,05 por caixa.",
  #   "product_type_id": 2,
  #   "details": "Antispam e antivírus, Aplicativo Type App, Painel de controle, Versão mobile.",
  #   "created_at": "2021-03-13T20:18:19.624Z",
  #   "updated_at": "2021-03-13T20:18:19.624Z",
  #   "status": "activated"
  #   },
  #   {
  #   "id": 4,
  #   "name": "Basico",
  #   "description": "descrição basico",
  #   "product_type_id": 2,
  #   "details": "detalhes basico",
  #   "created_at": "2021-03-28T05:36:32.609Z",
  #   "updated_at": "2021-03-28T05:36:32.609Z",
  #   "status": "activated"
  #   }
  # ]
  def product_type
    plans = Plan.where(product_type: find_product.fetch(:product_type_id))
    render json: plans, status: :ok
  end

  private

  def find_plan
    params.permit(:id)
  end

  def find_product
    params.permit(:product_type_id)
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :plan_all, only: %i[index create]
  before_action :products_all, only: %i[index create edit update]

  def index
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    return redirect_to plans_path, notice: t('.success') \
           if @plan.save

    flash.now[:alert] = t('.error')
    render :index
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    return redirect_to plans_path, notice: t('.success') \
           if @plan.update(plan_params)

    flash.now[:alert] = t('.error')
    render :edit
  end

  def destroy
    Plan.destroy(params[:id])
    redirect_back fallback_location: plans_path
  end

  def deactivate
    Plan.find(params[:id]).disabled!
    redirect_back fallback_location: plans_path
  end

  def activate
    Plan.find(params[:id]).activated!
    redirect_back fallback_location: plans_path
  end

  private

  def plan_params
    params.require(:plan).permit(:name, :description, :product_type_id,
                                 :details, :status)
  end

  def plan_all
    @plans = Plan.all
  end

  def products_all
    @products = ProductType.all
  end
end

app/views/plans/_form.html.erb
<%= form_with model: @plan, local: true, 
              class: 'ls-form ls-form-horizontal' do | form |%>
  <div class="ls-modal-body" id="myModalBody">
    <fieldset>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :description %>
        <%= form.text_area :description, rows: "1" %>
      </label>
      <label class="ls-label col-md-4">
        <%= form.label :product_type_id, class: 'ls-label-text' %>
        <div class="ls-custom-select">
          <%= form.collection_select :product_type_id, @products, :id, :name, class: 'ls-custom' %>
        </div>
      </label>
      <label class="ls-label col-md-4 col-xs-12">
        <%= form.label :details %>
        <%= form.text_area :details, rows: "1" %>
      </label>
      <label class="ls-label col-md-7">
          <%= form.label :status %>
        <label class="ls-label-text" style="margin-top: 9px;">
          <%= form.radio_button(:status, 'activated') %>
          <%= t('.status.activated') %>
        </label>
        <label class="ls-label-text" style="margin-top: 9px;">
          <%= form.radio_button(:status, 'disabled') %>
          <%= t('.status.disabled') %>
        </label>
      </label>
    </fieldset> 
  </div>
  <div class="ls-modal-footer">
    <%= form.submit class: 'ls-btn-primary' %>
  </div>
<% end %>

app/views/plans/edit.html.erb
 <h1 class="ls-title-intro ls-ico-calendar"><%= Plan.model_name.human(count: 1) %></h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @plan.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @plan.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<%= render 'form' %>

app/views/plans/index.html.erb
 <h1 class="ls-title-intro ls-ico-checkbox-unchecked">
  <%= Plan.model_name.human(count: 2) %>
 </h1>

<div class="ls-alert-danger"><%= alert %></div>
<div class="ls-alert-success"><%= notice %></div>

<% if @plan.errors.any? %>
<ul style="list-style-type:none">
  <h4><%= t('.errors_phrase') %>: </h4><br>
  <% @plan.errors.full_messages.each do |msg| %>
    <li>- <%= msg %></li>
  <% end %>
</ul>
 <br><br>
 <% end %>

<button data-ls-module="modal" data-target="#addPlan" 
        class="ls-btn-primary ls-ico-checkbox-unchecked"> <%= t('.add_button') %>
</button>

 <table class="ls-table ls-table-striped">
  <thead>
    <tr>
      <th class="hidden-xs"><%= Plan.human_attribute_name('id') %></th>
      <th><%= Plan.human_attribute_name('name') %></th>
      <th class="hidden-xs"><%= Plan.human_attribute_name('description') %></th>
      <th><%= ProductType.model_name.human %></th>
      <th class="hidden-xs"><%= Plan.human_attribute_name('details') %></th>
      <th><%= Plan.human_attribute_name('status') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @plans.each do | plan | %>
    <tr id=<%= "plan-#{plan.id}" %>>
      <td class="hidden-xs"><%= plan.id %></td>
      <td><%= plan.name %></td>
      <td class="hidden-xs"><%= plan.description %></td>
      <td><%= plan.product_type.name %></td>
      <td class="hidden-xs"><%= plan.details %></td>
      <td>
        <strong>
          <% if plan.status == 'activated' %>
            <%= link_to t('.status.deactivate'), deactivate_plan_path(plan), method: :post %>
          <% else %>
            <%= link_to t('.status.activate'), activate_plan_path(plan), method: :post %>
          <% end %>
        </strong>
      </td>
      <td class="hidden-xs">
        <%= link_to t('.edit_button'), edit_plan_path(plan), class: 'ls-btn' %> 
        <%= link_to '', plan, method: :delete, class: 'ls-btn-primary-danger ls-ico-remove',
                                     data: { confirm: t('.confirmation_deletion') }, 
                                     id: 'deletar_button' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render 'modal' %>

<br><br>