config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/apis', to: 'apis#index'
  root to: 'home#index'
  resources :periodicities, only: %i[index create update edit destroy]
  resources :product_types, only: %i[index create update edit destroy]
  resources :plans, only: %i[index create update edit destroy] do
    post 'deactivate', 'activate', on: :member
  end
  resources :prices, only: %i[index create update edit destroy]

  namespace 'api' do
    namespace 'v1' do
      resources :periodicities, only: :index
      resources :product_types, only: %i[index show] do
        resources :plans, only: :index, action: :product_type
      end
      resources :plans, only: %i[index show] do
        resources :prices, only: :index
      end
    end
  end
end

app/views/layouts/_app.html.erb
<div class="ls-topbar ">

<!-- Barra de Notificações -->
<div class="ls-notification-topbar">

<!-- Dropdown com detalhes da conta de usuário -->
<div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
  <a href="#" class="ls-ico-user">
    <span class="ls-name"><%= current_user.email %></span>
  </a>

  <nav class="ls-dropdown-nav ls-user-menu">
    <ul>
      <li><%= link_to t('.logout_button'), destroy_user_session_path, method: :delete %></li>
    </ul>
  </nav>
</div>
</div>

<span class="ls-show-sidebar ls-ico-menu"></span>

<a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-next"><span class="ls-text">Voltar à lista de serviços</span></a>

<!-- Nome do produto/marca com sidebar -->
<h1 class="ls-brand-name">
  <a href="home" class="ls-ico-earth">
    <small>Uma descrição ou outro nome</small>
    O nome do Produto
  </a>
</h1>

<!-- Nome do produto/marca sem sidebar quando for o pre-painel  -->
</div>


<aside class="ls-sidebar">

<div class="ls-sidebar-inner">
  <a href="/locawebstyle/documentacao/exemplos//pre-painel"  class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>

  <nav class="ls-menu">
    <ul>
      <li><%= link_to Periodicity.model_name.human(count: 2), periodicities_path, class: 'ls-ico-calendar' %></li>
      <li><%= link_to ProductType.model_name.human(count: 2), product_types_path, class: 'ls-ico-origins' %></li>
      <li><%= link_to Plan.model_name.human(count: 2), plans_path, class: 'ls-ico-checkbox-unchecked' %></li>
      <li><%= link_to Price.model_name.human(count: 2), prices_path, class: 'ls-ico-star' %></li>
      <li><%= link_to t('.apis_title'), apis_path, class: 'ls-ico-insert-template' %>
    </ul>
  </nav>


</div>
</aside>


<main class="ls-main">
  <div class="container-fluid">

    <%= yield %>

  </div>
</main>

<aside class="ls-notification">
  <nav class="ls-notification-list" id="ls-notification-curtain" style="left: 1716px;">
    <h3 class="ls-title-2">Notificações</h3>
    <ul>
      <li class="ls-dismissable">
        <a href="#">Blanditiis est est dolorem iure voluptatem eos deleniti repellat et laborum consequatur</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Similique eos rerum perferendis voluptatibus</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Qui numquam iusto suscipit nisi qui unde</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Nisi aut assumenda dignissimos qui ea in deserunt quo deleniti dolorum quo et consequatur</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
      <li class="ls-dismissable">
        <a href="#">Sunt consequuntur aut aut a molestiae veritatis assumenda voluptas nam placeat eius ad</a>
        <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
      </li>
    </ul>
  </nav>

  <nav class="ls-notification-list" id="ls-help-curtain" style="left: 1756px;">
    <h3 class="ls-title-2">Feedback</h3>
    <ul>
      <li><a href="#">&gt; quo fugiat facilis nulla perspiciatis consequatur</a></li>
      <li><a href="#">&gt; enim et labore repellat enim debitis</a></li>
    </ul>
  </nav>

  <nav class="ls-notification-list" id="ls-feedback-curtain" style="left: 1796px;">
    <h3 class="ls-title-2">Ajuda</h3>
    <ul>
      <li class="ls-txt-center hidden-xs">
        <a href="#" class="ls-btn-dark ls-btn-tour">Fazer um Tour</a>
      </li>
      <li><a href="#">&gt; Guia</a></li>
      <li><a href="#">&gt; Wiki</a></li>
    </ul>
  </nav>
</aside>

app/views/layouts/_sign.html.erb
<div class="ls-login-parent">
  <div class="ls-login-inner">
    <div class="ls-login-container">
      <div class="ls-login-box">
        <h1 class="ls-login-logo"><%= image_tag "logo-locaweb.png" %></h1>
        <div class="ls-alert-danger"><%= alert %></div>
        <div class="ls-alert-success"><%= notice %></div>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-light-green">
  <head>
    <title>Product</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- LOCASTYLE -->
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="description" content="Insira aqui a descrição da página.">
  </head>

  <body>
    <%= render 'layouts/app' if user_signed_in? %>
    <%= render 'layouts/sign' unless user_signed_in? %>
  </body>
</html>